parameters:
#    sdz_profile.example.class: Sdz\ProfileBundle\Example

services:
#    sdz_profile.example:
#        class: %sdz_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
